### ISSUE TITLE
Gnome 46 notifications are a mess

### ISSUE THREAD

**Issue by jorgeajimenezl** [vinceliuice/Colloid-gtk-theme#146]
Hi and sorry for bothering you with these stuff, normally I would fix it by myself, but I know about CSS as much as i know from how to be an astronaut.
AFAIS every woorks well in gnome 46, but the notifications looks a little weird:
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/18174581/96f215ee-e96d-4ef4-b383-388c81ea8532)

**Comment by Artofaj** [comment]
Can confirm the issue:
![Screenshot from 2024-03-26 13-59-11](https://github.com/pop-os/shell/assets/39367453/d1ba1d2f-7d2d-462a-90aa-792c54222be2)

**Comment by DarioZar** [comment]
The problem seems to be in this line here

https://github.com/vinceliuice/Colloid-gtk-theme/blob/6cf7ea0237080ebe3baa4fa74275c7f453dbe39a/src/sass/gnome-shell/common/_notifications.scss#L11

I tried commenting it and the notifications look like this
![Schermata del 2024-03-27 01-37-49](https://github.com/vinceliuice/Colloid-gtk-theme/assets/15327563/385f3c5f-8053-48ed-aa72-9085946f4760)

**Comment by zerodeusx** [comment]
Having the same problem, also a problem from another theme
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/72922834/32441ecb-5742-4301-9798-9b662b16020d)
(didn't upload my screenshot since I already uninstalled the theme, can't even use nautilus and some other programs)
